Repository BhaktiMore18/Pouranik, pull requests merged in 2025-08, with the labels that each got.

#116 Added Filter and Sort feature
  API_KEY_SETUP_GUIDE.md
  FILTER_FIX_SUMMARY.md
  SORTING_AND_FILTERING_FEATURES.md
  TESTING_GUIDE.md
  backend/.env.example
  frontend/.env.example
  frontend/package-lock.json
  frontend/src/App.css
  frontend/src/components/QuickFilters.jsx
  frontend/src/components/SortAndFilterControls.jsx
  frontend/src/pages/Explore.jsx
  frontend/src/services/bookService.js
  frontend/src/utils/filterPreferences.js
  setup.sh
Labels: enhancement, gssoc25, level 2

#119 Footer Color Inconsistency & Responsive Improvements - Closes #102
  frontend/src/components/Footer.jsx
Labels: frontend, gssoc25, level 2, improvement

#138 enhanced the footer section background in modes
  frontend/src/components/Footer.jsx
Labels: good first issue, frontend, gssoc25, level 1

#165 Style navbar size, login and signup text-color
  frontend/src/components/AuthForm.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/pages/SignIn.jsx
Labels: good first issue, frontend, gssoc25, level 1

#169 separating different sections with fancy border
  frontend/src/pages/Genres.css
  frontend/src/pages/Genres.jsx
Labels: good first issue, gssoc25, level 1

#159 Fix/auth form height center
  frontend/src/pages/SignIn.jsx
Labels: good first issue, gssoc25, level 1

#118 AI Summarizer for the Books
  frontend/src/pages/AISummarySection.jsx
  frontend/src/pages/BookDetail.jsx
  frontend/src/services/AISummaryService.js
Labels: enhancement, gssoc25, level 3

#186 Increase size of social media icons in Footer
  frontend/src/components/Footer.jsx
Labels: gssoc25, level 1

#190 Added Social's -linkedin in footer
  frontend/src/components/Footer.jsx
Labels: good first issue, gssoc25, level 1

#207 Add project structure in Readme.md
  README.md
Labels: documentation, good first issue, gssoc25, level 1
