Repository BhaktiMore18/Pouranik, pull requests merged in 2025-09, with the labels that each got.

#215 Fixes #209: Add count-up animation to stats section
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/Genres.jsx
  frontend/src/pages/Home.jsx
Labels: gssoc25, level 1, improvement

#240 notfound page
  frontend/src/components/Notfound.jsx
  frontend/src/routes/AppRoutes.jsx
Labels: gssoc25, level 2

#242 added proper redirection changes
  frontend/src/pages/Community.jsx
Labels: gssoc25, level 1
